using System;
using System.IO;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.AI;
namespace ServiceGameV2 {
 public sealed class ServiceV5Smoke:MonoBehaviour {
  ServiceDirector d;string dir;
  public void Run(ServiceDirector director){d=director;dir=Environment.GetEnvironmentVariable("SERVICE_CAPTURE_DIR");if(string.IsNullOrEmpty(dir))dir=Path.Combine(Application.persistentDataPath,"SmokeV5");Directory.CreateDirectory(dir);StartCoroutine(Guard());}
  IEnumerator Guard(){var stack=new Stack<IEnumerator>();stack.Push(Check());bool failed=false;while(stack.Count>0){object next=null;bool more=false;try{more=stack.Peek().MoveNext();if(more)next=stack.Peek().Current;}catch(Exception e){Debug.LogException(e);failed=true;break;}if(!more){stack.Pop();continue;}if(next is IEnumerator nested){stack.Push(nested);continue;}yield return next;}d.Player.SmokeWalk=Vector2.zero;d.Player.SmokeThrottle=0;for(int i=0;i<6;i++)PlayerPrefs.DeleteKey("SERVICE.test.result"+i);PlayerPrefs.DeleteKey("SERVICE.test.night");PlayerPrefs.Save();var result=(failed?"FAIL":"PASS")+": SERVICE_V16_FULL (five distinct properties, physical access and escape, friendly deliveries, pursuit and watcher rules, crouch/jump, live mirror, radio, scalable interface, retry checkpoint, surfaces, needle, pause, route save)";File.WriteAllText(Path.Combine(dir,"smoke-result.txt"),result);Debug.Log(result);Application.Quit(failed?1:0);}
  void Require(bool pass,string message){if(!pass)throw new Exception("SERVICE_V5: "+message);}
  IEnumerator Shot(string name){yield return null;yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Path.Combine(dir,name+".png"));yield return new WaitForSecondsRealtime(.2f);}
  IEnumerator Navigate(Vector3 target,bool sprint){
   Require(NavMesh.SamplePosition(d.Scene.Walker.transform.position,out var from,1.2f,NavMesh.AllAreas),"Start outside navigation");Require(NavMesh.SamplePosition(target,out var goal,1.2f,NavMesh.AllAreas),"Goal outside navigation");
   var path=new NavMeshPath();Require(NavMesh.CalculatePath(from.position,goal.position,NavMesh.AllAreas,path)&&path.status==NavMeshPathStatus.PathComplete,"No complete path to "+target);
   float start=Time.time;d.Player.SmokeSprint=sprint;
   foreach(var corner in path.corners){Debug.Log("V5_CORNER start="+d.Scene.Walker.transform.position+" target="+corner+" sprint="+sprint);float until=Time.time+35;while(Vector2.Distance(new Vector2(d.Scene.Walker.transform.position.x,d.Scene.Walker.transform.position.z),new Vector2(corner.x,corner.z))>.15f&&Time.time<until){if(sprint&&Vector3.Distance(d.Scene.View.transform.position,d.Scene.Car.position+Vector3.up)<3.2f){d.Player.SmokeWalk=Vector2.zero;d.Player.SmokeSprint=false;Debug.Log("V5_WALK escape seconds="+(Time.time-start));yield break;}Require(!d.Horror.Caught,"Caught during escape at property "+d.Horror.PropertyIndex+" position="+d.Scene.Walker.transform.position+" target="+corner+" elapsed="+(Time.time-start));d.Player.SmokeFace(corner);d.Player.SmokeWalk=Vector2.up;yield return null;}d.Player.SmokeWalk=Vector2.zero;Require(Time.time<until,"Physical route blocked: "+d.Scene.Walker.transform.position+" toward "+corner);}
   Require(Mathf.Abs(d.Scene.Walker.transform.position.y-goal.position.y)<.45f,"Wrong floor at "+target);Debug.Log("V5_WALK "+(sprint?"escape":"approach")+" seconds="+(Time.time-start));d.Player.SmokeSprint=false;
   var delivery=d.Scene.Properties.FirstOrDefault(p=>Vector3.Distance(p.TableApproach.position,target)<.6f);if(delivery){var delta=delivery.DeliveryPoint.position-d.Scene.View.transform.position;d.Player.SmokeLook(Mathf.Atan2(delta.x,delta.z)*Mathf.Rad2Deg,-Mathf.Atan2(delta.y,new Vector2(delta.x,delta.z).magnitude)*Mathf.Rad2Deg);yield return new WaitForSeconds(.2f);}
  }
  IEnumerator V15Rules(){
   d.BeginShift(0);d.PaperOpen=false;
   // Walk directly to the Bell side table before contacting its resident.
   var bell=d.Property(4);d.Player.SmokePlaceWalker(bell.TableApproach.position);yield return null;d.Attempt(4,ServiceResult.LeftAtDoor);Require(d.ResultAt(4)==ServiceResult.Pending&&!d.AccessGranted(4),"Bell side entrance cannot bypass delivery interaction");
   var stair=FindObjectsByType<ServiceStairZone>().OrderBy(z=>Vector3.Distance(z.Area.center,d.Property(1).Door.position)).First();
   var foot=stair.Area.center;foot.y=stair.Area.min.y+.4f;d.Player.SmokePlaceWalker(foot);yield return new WaitForSeconds(.3f);d.Player.SmokeJump=true;yield return null;Require(d.Player.OnStairs&&d.Player.VerticalSpeed<=0,"Jump suppressed within authored stair bounds");
   d.Player.TeleportCar(d.Scene.Depot.position,Quaternion.identity);d.Player.EnterCar();d.Player.StartEngine();yield return new WaitForSeconds(.8f);d.Player.SmokeThrottle=1;yield return new WaitForSeconds(1);Require(d.Audio.EngineAudible,"Engine loop audible during gameplay");d.ToggleDocument(true);yield return new WaitForSeconds(.2f);Require(!d.Audio.EngineAudible&&d.Player.Speed==0,"Map stops rolling and mutes engine");d.ToggleDocument(true);yield return null;Require(d.Audio.EngineAudible,"Engine audio resumes on closing map");d.Player.SmokeThrottle=0;d.Player.StopEngine();
   var tree=d.Scene.GetComponentsInChildren<CapsuleCollider>().First(c=>c.name.StartsWith("PF Conifer")&&Vector3.Distance(c.transform.position,d.Scene.Depot.position)<45);
   var target=tree.bounds.center;target.y=tree.bounds.min.y;var start=target-Vector3.forward*8;d.Player.TeleportCar(start,Quaternion.identity);d.Player.EnterCar();d.Player.SmokeThrottle=1;int impacts=d.Audio.CollisionsPlayed;yield return new WaitForSeconds(3.5f);d.Player.SmokeThrottle=0;Require(d.Audio.CollisionsPlayed>impacts,"Physical tree strike plays collision recording");Require(d.Scene.Car.position.z<target.z-1,"Vehicle cannot pass through tree trunk");yield return Shot("tree-collision");d.Player.StopEngine();
   d.Player.TeleportCar(d.Scene.Depot.position,Quaternion.identity);d.Player.SmokePlaceWalker(d.Scene.Car.position-Vector3.forward*5);d.Player.SmokeFace(d.Scene.Car.position);yield return new WaitForSeconds(.3f);yield return Shot("car-rear-exterior");
   d.BeginShift(0);d.PaperOpen=false;d.Player.TeleportCar(new Vector3(-4,.05f,374),Quaternion.identity);d.Player.EnterCar();
   var lane=new[]{new Vector3(-4,0,380),new Vector3(-11,0,385),new Vector3(-26,0,385),new Vector3(-32,0,379),new Vector3(-32,0,300),new Vector3(-32,0,200),new Vector3(-32,0,100),new Vector3(-32,0,-12),new Vector3(-26,0,-18),new Vector3(-6,0,-18),new Vector3(0,0,-12),new Vector3(0,0,0)};
   float deadline=Time.time+140;int waypoint=0;
   foreach(var destination in lane){while(Vector2.Distance(new Vector2(d.Scene.Car.position.x,d.Scene.Car.position.z),new Vector2(destination.x,destination.z))>3&&Time.time<deadline){var dir=destination-d.Scene.Car.position;dir.y=0;float angle=Vector3.SignedAngle(d.Scene.Car.forward,dir,Vector3.up);d.Player.SmokeSteering=Mathf.Clamp(angle/22,-1,1);d.Player.SmokeThrottle=Mathf.Abs(angle)>35?.28f:.75f;yield return null;}Require(Time.time<deadline,"Return road driving blocked at waypoint "+waypoint+" car="+d.Scene.Car.position);if(waypoint==2||waypoint==5){d.Player.SmokeThrottle=0;d.Player.HoldVehicle();yield return Shot("return-road-"+waypoint);}waypoint++;}
   d.Player.SmokeThrottle=d.Player.SmokeSteering=0;d.Player.StopEngine();Require(Vector3.Distance(d.Scene.Car.position,d.Scene.Depot.position)<13,"Return loop reaches depot without teleporting");yield return Shot("return-depot");
   d.BeginShift(0);d.PaperOpen=false;
  }
  IEnumerator BellProbe(){
   d.BeginShift(0);d.PaperOpen=false;var p=d.Property(4);
   d.Player.TeleportCar(p.Gate.position-p.Gate.forward*3,Quaternion.LookRotation(p.Gate.forward));d.Player.SmokePlaceWalker(p.Door.position+p.Door.forward*1.2f);d.Player.SmokeFace(p.Door.position);yield return new WaitForSeconds(.2f);
   d.Attempt(4,ServiceResult.Served);yield return new WaitForSeconds(3.3f);
   var away=p.Gate.position-d.Scene.Walker.transform.position;away.y=0;yield return Navigate(d.Scene.Walker.transform.position+away.normalized*11,false);
   while(d.Horror.ForcedLook)yield return null;yield return Shot("bell-probe-reveal");yield return Navigate(p.Gate.position-p.Gate.forward*2,true);
   bool idle=Array.IndexOf(Environment.GetCommandLineArgs(),"-serviceBellIdle")>=0;bool reverse=Array.IndexOf(Environment.GetCommandLineArgs(),"-serviceBellReverse")>=0;d.Player.EnterCar();d.Player.StartEngine();float until=Time.time+8;float next=0;
   while(Time.time<until){if(Time.time>next){next=Time.time+.5f;Debug.Log("BELL_PROBE phase="+d.Horror.Phase+" car="+d.Scene.Car.position+" monster="+d.Horror.Agent.transform.position+" speed="+d.Player.Speed+" ignition="+d.Player.IsStarting+" blocker="+d.Player.LastVehicleObstruction);}if(Time.time>until-6.5f&&!idle)d.Player.SmokeThrottle=reverse?-1:1;yield return null;}
   d.Player.SmokeThrottle=0;yield return Shot("bell-probe-result");Require(idle?d.Horror.Caught:d.Horror.Phase==PursuitPhase.Escaped,"Bell ignition probe failed, phase="+d.Horror.Phase+" blocker="+d.Player.LastVehicleObstruction);
  }  IEnumerator Check(){
   if(Array.IndexOf(Environment.GetCommandLineArgs(),"-serviceBell")>=0){yield return BellProbe();yield break;}
   Require(AudioListener.volume==0,"Tests must start muted");
   var glass=d.Scene.Cockpit.transform.Find("Rearview glass");var glassMesh=glass.GetComponent<MeshFilter>().sharedMesh;var glassMat=glass.GetComponent<Renderer>().sharedMaterial;var uvScale=glassMat.GetTextureScale("_BaseMap");
   Require(uvScale==d.Scene.MirrorUVScale,"Mirror uses editor-verified upright reflected UV mapping");
   Require(RenderSettings.fogDensity>=.025f&&RenderSettings.fogColor.b>.4f,"Reference fog applied at runtime");
   var thickets=d.Scene.transform.Find("Forest understory thickets");Require(thickets&&thickets.childCount>500,"Dense forest patches installed");
   Require(Resources.LoadAll<AudioClip>("Audio/V5/brush").Length>=6&&Resources.Load<AudioClip>("Audio/V5/insects/insects_0"),"Recorded forest variations installed");
   float introLimit=Time.realtimeSinceStartup+30;while(d.Presentation.IntroTextAlpha<.75f&&Time.realtimeSinceStartup<introLimit)yield return null;Require(d.Presentation.IntroVisible&&d.Presentation.IntroTextAlpha>.5f,"Headphone card fades in");yield return Shot("headphones");while(d.Presentation.IntroVisible&&Time.realtimeSinceStartup<introLimit)yield return null;Require(!d.Presentation.IntroVisible,"Headphone card fades out");
   var menuPosition=d.Scene.View.transform.position;yield return new WaitForSeconds(.7f);Require(Vector3.Distance(menuPosition,d.Scene.View.transform.position)>.001f,"Title camera moves");Require(d.Scene.Rain.isPlaying&&d.Scene.Rain.particleCount>0,"Rain renders on title");yield return Shot("00-title");d.HUD.SmokeOptions(true);yield return Shot("settings");Screen.SetResolution(960,720,false);yield return new WaitForSeconds(.8f);yield return Shot("settings-4x3");Screen.SetResolution(1280,720,false);yield return new WaitForSeconds(.8f);d.HUD.SmokeOptions(false);
   d.Storm.FlashesEnabled=true;d.Storm.TriggerLightning();yield return new WaitForSeconds(.05f);Require(d.Storm.FlashStrength>.1f,"Lightning illuminates scene");yield return Shot("manor-lightning");yield return new WaitForSeconds(.8f);Require(d.Storm.FlashStrength==0,"Lightning recovers");
   yield return V15Rules();
   d.BeginShift(0);Require(d.Docket.Count==5,"First shift needs five stops");Require(d.Docket.Select(e=>d.Property(e.Property).Template).Distinct().Count()==5,"Repeated building template");yield return Shot("01-docket");d.MapOpen=true;yield return Shot("02-map");Require(d.HUD.MapPins==5&&d.HUD.MapSegments>20,"Map contains every stop and actual curved road");d.ToggleDocument(true);Require(!d.PaperOpen,"M closes map");d.ToggleDocument(true);Require(d.PaperOpen&&d.MapOpen,"M opens map");d.ToggleDocument(false);Require(d.PaperOpen&&!d.MapOpen,"Tab changes map to docket");d.ToggleDocument(false);Require(!d.PaperOpen,"Tab closes docket");
   d.Player.StartEngine();yield return new WaitForSeconds(.8f);d.Player.SmokeThrottle=1;yield return new WaitForSeconds(2);Require(d.Vehicle.WiperAngle==0,"Authored parked wipers remain unobtrusive");yield return Shot("driving-view");d.Player.SmokeThrottle=0;Require(d.Player.Speed>1,"Car moves");var needle=d.Scene.SpeedNeedle.up;var axis=d.Scene.SpeedNeedle.parent;float angle=Mathf.Lerp(220,-40,d.Player.Speed*2.237f/60)*Mathf.Deg2Rad;Require(Vector3.Dot(needle,axis.TransformDirection(new Vector3(Mathf.Cos(angle),Mathf.Sin(angle),0)))>.98f,"Speed needle follows dial");d.Player.SmokeSteering=1;yield return new WaitForSeconds(.3f);Require(d.Player.SteeringInput>.1f&&d.Player.SteeringInput<1,"Steering input ramps gradually");d.Player.SmokeSteering=0;d.Player.SmokeBrake=true;yield return new WaitForSeconds(.8f);Require(d.Player.Speed<.05f,"Brake stops car");d.Player.SmokeBrake=false;d.Player.SmokeThrottle=-1;yield return new WaitForSeconds(.6f);Require(d.Player.SignedSpeed<-.1f,"Reverse engages after stopping");d.Player.SmokeThrottle=0;d.Player.StopEngine();d.Player.SmokeLook(0,24);yield return new WaitForSeconds(.5f);yield return Shot("03-cockpit");
   Require(d.Scene.Cockpit.name=="Tyble authored cabin","Authored cabin installed");Require(d.Vehicle.StationsAvailable&&d.Vehicle.MirrorLive,"Radio tracks and live rearview camera");d.Vehicle.ToggleRadio();Require(d.Vehicle.RadioOn,"Radio power");d.Vehicle.NextStation();Require(d.Vehicle.Station==1,"Radio tuning");d.Vehicle.NextStation();Require(d.Vehicle.Station==2&&d.Vehicle.StationsAvailable,"Third licensed station loads");yield return Shot("radio");d.Player.SmokeLook(0,-12);yield return new WaitForSeconds(.5f);yield return Shot("rearview");d.Vehicle.ToggleRadio();
   d.Player.SmokeLook(36,14);yield return new WaitForSeconds(.4f);yield return Shot("cabin-passenger");d.Player.SmokeLook(-48,10);yield return new WaitForSeconds(.4f);yield return Shot("cabin-driver-door");d.Player.SmokeLook(0,0);yield return new WaitForSeconds(.4f);yield return Shot("cabin-forward");
   var rainfall=d.Scene.Rain;Require(rainfall.main.simulationSpace==ParticleSystemSimulationSpace.World,"Rain uses world coordinates");int removed=d.Storm.CabinDropsRemoved;var outside=d.Scene.Car.position+Vector3.up*6;rainfall.SetParticles(new[]{new ParticleSystem.Particle{position=d.Scene.View.transform.position,startLifetime=3,remainingLifetime=3,startSize=.02f},new ParticleSystem.Particle{position=outside,startLifetime=3,remainingLifetime=3,startSize=.02f}},2);yield return new WaitForSeconds(.1f);Require(d.Storm.CabinDropsRemoved>removed,"Rain inside cabin is removed");var drops=new ParticleSystem.Particle[rainfall.main.maxParticles];int dropCount=rainfall.GetParticles(drops);Require(drops.Take(dropCount).Any(particle=>particle.startLifetime==3&&Vector2.Distance(new Vector2(particle.position.x,particle.position.z),new Vector2(outside.x,outside.z))<.5f),"Outdoor rain survives cabin exclusion");
   Require(Resources.LoadAll<AudioClip>("Audio/V5/grass").Length>4&&Resources.LoadAll<AudioClip>("Audio/V5/wood").Length>4,"Footstep variations");
   var first=d.Property(0);d.Player.SmokePlaceWalker(first.ApproachRoute[4]);d.Player.SmokeFace(first.ApproachRoute[10]);yield return new WaitForSeconds(.3f);d.Player.SmokeCrouch=true;yield return new WaitForSeconds(.3f);Require(d.Player.Crouched&&d.Scene.Walker.height<1.2f,"Ctrl crouches");var ceiling=GameObject.CreatePrimitive(PrimitiveType.Cube);ceiling.name="Smoke headroom blocker";ceiling.transform.position=d.Scene.Walker.transform.position+Vector3.up*1.5f;ceiling.transform.localScale=new Vector3(2,.15f,2);Physics.SyncTransforms();d.Player.SmokeCrouch=false;yield return new WaitForSeconds(.2f);Require(d.Player.Crouched,"Ceiling prevents standing");Destroy(ceiling);yield return new WaitForSeconds(.3f);Require(!d.Player.Crouched,"Clear headroom restores standing");float ground=d.Scene.Walker.transform.position.y;d.Player.SmokeJump=true;yield return new WaitForSeconds(.22f);Require(d.Scene.Walker.transform.position.y>ground+.3f,"Jump leaves the ground");yield return new WaitForSeconds(.8f);Require(Mathf.Abs(d.Scene.Walker.transform.position.y-ground)<.15f,"Jump lands on ground");var forward=d.Scene.Walker.transform.forward;var origin=d.Scene.Walker.transform.position;
   d.Player.SmokeSprint=true;d.Player.SmokeWalk=Vector2.up;d.Player.SmokeLookBack=-1;yield return new WaitForSeconds(.4f);
   Require(Vector3.Dot(d.Scene.Walker.transform.forward,forward)>.99f&&Vector3.Dot(d.Scene.Walker.transform.position-origin,forward)>1,"Looking back preserves forward running");Require(Vector3.Dot(d.Scene.View.transform.forward,forward)<-.8f&&d.Player.InteractionSuppressed,"Q sees behind without interaction");yield return Shot("look-back-left");
   d.Player.SmokeLookBack=1;yield return new WaitForSeconds(.5f);Require(d.Player.LookBackAngle>150,"E looks over right shoulder");d.Player.SmokeLookBack=0;d.Player.SmokeWalk=Vector2.zero;d.Player.SmokeSprint=false;yield return new WaitForSeconds(.4f);Require(Mathf.Abs(d.Player.LookBackAngle)<1&&!d.Player.InteractionSuppressed,"Release restores forward view and interaction");
   var zone=d.Scene.transform.Find("Storm verge planting").GetComponentInChildren<ServiceBrushZone>();Require(zone&&ServiceBrushZone.Active.Count>100,"Bush contact zones exist");d.Player.SmokePlaceWalker(zone.Center);d.Player.SmokeFace(zone.Center+Vector3.right*3);yield return new WaitForSeconds(1.1f);int brushCount=d.Audio.BrushEvents;d.Player.SmokeWalk=Vector2.up;yield return new WaitForSeconds(.22f);d.Player.SmokeWalk=Vector2.zero;Require(d.Audio.BrushEvents>brushCount,"Walking through bushes rustles");
   d.Audio.Footstep(d.Scene.Walker.transform.position);Require(d.Audio.LastFootstepPool.StartsWith("wet"),"Exposed footsteps use wet recordings");
   foreach(int index in new[]{0,3,1,4,5}){
    Require(AudioListener.volume==0,"Tests must remain muted");
    var p=d.Property(index);d.Player.TeleportCar(p.Gate.position-p.Gate.forward*3,Quaternion.LookRotation(p.Gate.forward));if(index==0){d.Player.EnterCar();yield return new WaitForSeconds(.4f);var prior=RenderTexture.active;RenderTexture.active=d.Vehicle.MirrorTexture;var texture=new Texture2D(768,192,TextureFormat.RGB24,false);texture.ReadPixels(new Rect(0,0,768,192),0,0);texture.Apply();File.WriteAllBytes(Path.Combine(dir,"mirror-feed.png"),texture.EncodeToPNG());Destroy(texture);RenderTexture.active=prior;}d.Player.SmokePlaceWalker(p.Gate.position);d.Player.SmokeFace(p.Door.position);yield return Shot("property-"+index+"-approach");
    if(index==0){yield return Navigate(p.ApproachRoute[p.ApproachRoute.Length/2],false);d.Player.SmokeFace(p.Door.position+Vector3.up);yield return new WaitForSeconds(.4f);yield return Shot("forest-reference");if(d.Scene.transform.Find("Scanned woodland details")){d.Player.SmokeLook(d.Scene.Walker.transform.eulerAngles.y,25);yield return Shot("woodland-ground");d.Player.SmokeLook(d.Scene.Walker.transform.eulerAngles.y-65,12);yield return Shot("woodland-verge");d.Player.SmokeFace(p.Door.position);float seconds=0;for(int f=0;f<120;f++){yield return null;seconds+=Time.unscaledDeltaTime;}File.WriteAllText(Path.Combine(dir,"frame-sample.txt"),"120 stationary forest frames: "+(120/seconds).ToString("F1")+" FPS. Not a full performance benchmark.");}}
    if(!d.IsFriendly(index)){yield return Navigate(p.Door.position+p.Door.forward*1.2f,false);d.Player.SmokeFace(p.Door.position);d.Attempt(index,ServiceResult.Served);yield return new WaitForSeconds(2.3f);Require(!d.Busy&&!d.Horror.Active,"Knock opens hostile entrance without prematurely starting chase");yield return Shot("harrow-door");}
    if(!d.IsFriendly(index)){yield return Navigate(p.TableApproach.position,false);Require(d.NearbyDoor()==index,"Delivery unavailable at property "+index);Require(d.Audio.SurfaceAt(d.Scene.Walker.transform.position)=="wood","Interior wood surface "+index);d.Audio.Footstep(d.Scene.Walker.transform.position);Require(d.Audio.LastFootstepPool=="wood","Sheltered interior footsteps stay dry");yield return new WaitForSeconds(.15f);Require(!d.Scene.Rain.isPlaying,"Rain stays outside interiors");d.Player.SmokeFace(p.DeliveryPoint.position);yield return Shot("property-"+index+"-interior");}if(d.IsFriendly(index)){
     yield return Navigate(p.Door.position+p.Door.forward*1.2f,false);d.Player.SmokeFace(p.Door.position+Vector3.up);yield return new WaitForSeconds(.2f);Require(d.NearbyKnockDoor()==index,"Front door knock available");yield return Shot("property-"+index+"-door");int knocks=d.KnockCount;d.Attempt(index,ServiceResult.Served);Require(d.Busy&&d.KnockCount==knocks+1,"Knocking starts");yield return new WaitForSeconds(3.3f);Require(d.ResultAt(index)==ServiceResult.Served&&!d.Horror.Active,"Friendly delivery accepted without threat");yield return Shot("property-"+index+"-presence");
     if(index==0){Require(d.Life.DogPresent&&d.Scene.GetComponentInChildren<ServiceResidents>(),"Authored dog and residents installed");var dog=d.Scene.transform.Find("Correll yard dog");d.Player.SmokePlaceWalker(dog.position+p.Door.forward*3);d.Player.SmokeFace(dog.position+Vector3.up*.45f);yield return null;d.Player.SmokeLook(d.Scene.Walker.transform.eulerAngles.y,20);d.Scene.Flashlight.enabled=true;d.Life.Bark();yield return new WaitForSeconds(.5f);foreach(var r in dog.GetComponentsInChildren<SkinnedMeshRenderer>())Debug.Log("V15_DOG rendered bounds="+r.bounds+" root="+dog.position);yield return Shot("yard-dog");d.Scene.Flashlight.enabled=false;}
     if(index==4){
      int ambushes=d.Horror.ReturnAmbushes;var away=p.Gate.position-d.Scene.Walker.transform.position;away.y=0;var trigger=d.Scene.Walker.transform.position+away.normalized*11;
      yield return Navigate(trigger,false);Require(d.Horror.Active&&d.Horror.ReturnAmbushes==ambushes+1,"Bell return-path ambush fires once");d.Player.SmokeWalk=Vector2.zero;while(d.Horror.ForcedLook)yield return null;Require(!d.Horror.ForcedLook&&d.Horror.Active,"Forced glance releases before escape");Require(Vector3.Dot(d.Scene.View.transform.forward,d.Scene.Walker.transform.forward)>.98f,"Glance returns to forward view without changing running direction");yield return Shot("bell-return-ambush");yield return Navigate(p.Gate.position-p.Gate.forward*2,true);Require(!d.Horror.Caught,"Bell return pursuit is escapable");d.Player.EnterCar();yield return null;Require(d.Horror.Active,"Entering the car does not dismiss the ignition ambush");d.Player.StartEngine();Require(d.Player.FailedIgnition,"Scripted ignition failure armed");yield return new WaitForSeconds(1.5f);Require(d.Player.IsStarting&&d.Horror.Active&&!d.Horror.Caught,"Monster keeps approaching during failed ignition");yield return Shot("failed-ignition");d.Player.SmokeThrottle=1;float escapeBy=Time.time+6;while(d.Horror.Active&&Time.time<escapeBy)yield return null;d.Player.SmokeThrottle=0;Require(d.Horror.Phase==PursuitPhase.Escaped,"Drive away after stalled ignition");d.Player.StopEngine();
     }else d.Player.EnterCar();continue;
    }
    d.Attempt(index,ServiceResult.LeftAtDoor);Require(d.Horror.Active&&d.Horror.PropertyIndex==index,"Encounter did not start "+index);
    if(index==5){
     float deadline=Time.time+25;while(!d.Horror.Caught&&Time.time<deadline)yield return null;Require(d.Horror.Phase==PursuitPhase.Attack,"A stationary player is physically caught");yield return new WaitForSeconds(.15f);yield return Shot("pursuit-windup");yield return new WaitForSeconds(.2f);
     Require(d.Scene.Entity.GetComponentsInChildren<Animator>().Any(a=>a.GetCurrentAnimatorStateInfo(0).IsName("Attack")),"Authored attack animation plays");yield return Shot("pursuit-contact");yield return new WaitForSeconds(4.6f);Require(d.ResultAt(5)==ServiceResult.Pending&&d.ResultAt(4)==ServiceResult.Served,"Capture retries only current property");
     yield return Navigate(p.TableApproach.position,false);d.Attempt(index,ServiceResult.LeftAtDoor);Require(d.Horror.Active,"Pursuit can restart after contact");
    }
    d.Pause();if(index==1)yield return Shot("pause");float elapsed=d.Horror.Elapsed;yield return new WaitForSecondsRealtime(.15f);Require(AudioListener.pause&&Mathf.Abs(elapsed-d.Horror.Elapsed)<.01f,"Pause freezes audio and encounter");d.Resume();
    if(index==3){
     Require(p.CreatureVariant==3 && d.Scene.EntityVariants.Length==4,"Distinct Demon variant installed"); d.Player.SmokeFace(d.Horror.Agent.transform.position); yield return Shot("watcher-presence");
     yield return new WaitForSeconds(1.2f);d.Player.SmokeWalk=Vector2.up;d.Player.SmokeSprint=false;yield return new WaitForSeconds(.25f);d.Player.SmokeWalk=Vector2.zero;d.Player.SmokeSprint=false;Require(d.Horror.Caught,"Walking without Shift must fail watcher");Require(d.Horror.Phase==PursuitPhase.Attack,"Capture plays visible attack first");yield return Shot("watcher-attack");yield return new WaitForSeconds(1.3f);yield return Shot("watcher-failure");yield return new WaitForSeconds(5.2f);Require(d.ResultAt(0)!=ServiceResult.Pending&&d.ResultAt(3)==ServiceResult.Pending,"Retry preserves other deliveries");
     yield return Navigate(p.TableApproach.position,false);d.Attempt(index,ServiceResult.LeftAtDoor);d.Player.SmokeFace(d.Scene.Walker.transform.position+(d.Scene.Walker.transform.position-d.Horror.Agent.transform.position));d.Player.SmokeSprint=true;yield return new WaitForSeconds(9.6f);d.Player.SmokeSprint=false;Require(d.Horror.Phase==PursuitPhase.Escaped,"Still, facing away with Shift held must dismiss watcher");yield return Shot("watcher-dismissed");d.Player.EnterCar();
    }else{
     d.Player.SmokeFace(d.Horror.Agent.transform.position);yield return new WaitForSeconds(3.3f);Require(d.Horror.Phase==PursuitPhase.Chase,"Pursuit starts "+index);Require(d.Horror.Agent.speed>=5.25f,"Stronger chase speed");Require(d.Horror.SpawnPathDistance>7,"Longer initial escape distance "+index+" = "+d.Horror.SpawnPathDistance);Require(d.Audio.ChaseLevel>.1f,"Chase music rises");yield return Shot("property-"+index+"-presence");yield return Navigate(p.Gate.position-p.Gate.forward*2,true);Require(d.Horror.Active,"Must escape alive "+index);Require(Vector3.Distance(d.Scene.View.transform.position,d.Scene.Car.position+Vector3.up)<3.5f,"Reach car interaction "+index);d.Player.EnterCar();yield return null;Require(d.Horror.Phase==PursuitPhase.Escaped,"Car escape "+index);Require(d.Audio.MonsterSteps>0&&d.Audio.LastMonsterFootstepPool.StartsWith("monster"),"Positional recorded pursuit steps play "+index);
    }
   }
   Require(d.AllResolved,"All five notices resolved");Require(d.Audio.MonsterSteps>20&&d.Audio.MonsterStepSurfaces.Contains("wood")&&d.Audio.MonsterStepSurfaces.Any(surface=>surface!="wood"),"Pursuit footsteps cover indoors and outdoors");Debug.Log("V13_MONSTER_STEPS="+d.Audio.MonsterSteps+" surfaces="+string.Join(",",d.Audio.MonsterStepSurfaces));d.Player.TeleportCar(d.Scene.Depot.position,Quaternion.identity);Require(d.TryFinishShift(),"File five-stop report");yield return Shot("09-report");d.Title();Require(d.HasSavedRoute,"Route saved");d.ContinueRoute();Require(d.NightIndex==1&&d.Docket.Count==5,"Saved second shift");d.MapOpen=true;yield return Shot("second-shift-map");Require(d.HUD.MapPins==5,"Second shift map retains all stops");d.BeginShift(2);d.MapOpen=true;yield return Shot("third-shift-map");Require(d.HUD.MapPins==2,"Third shift map uses current docket");d.PaperOpen=false;var late=d.Property(2);d.Player.TeleportCar(late.Gate.position-late.Gate.forward*2,Quaternion.LookRotation(late.Gate.forward));d.Player.SmokePlaceWalker(late.Gate.position);yield return Navigate(late.Door.position+late.Door.forward*1.2f,false);d.Player.SmokeFace(late.Door.position);yield return Shot("county-route9-clear");d.BeginShift(0);Require(d.Horror.Phase==PursuitPhase.Dormant,"Restart resets encounters");
  }
 }
}





