using System;
using System.IO;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.AI;
namespace ServiceGameV2 {
 public sealed class ServiceV5Smoke:MonoBehaviour {
  ServiceDirector d;string dir;
  public void Run(ServiceDirector director){d=director;dir=Environment.GetEnvironmentVariable("SERVICE_CAPTURE_DIR");if(string.IsNullOrEmpty(dir))dir=Path.Combine(Application.persistentDataPath,"SmokeV5");Directory.CreateDirectory(dir);StartCoroutine(Guard());}
  IEnumerator Guard(){var stack=new Stack<IEnumerator>();stack.Push(Check());bool failed=false;while(stack.Count>0){object next=null;bool more=false;try{more=stack.Peek().MoveNext();if(more)next=stack.Peek().Current;}catch(Exception e){Debug.LogException(e);failed=true;break;}if(!more){stack.Pop();continue;}if(next is IEnumerator nested){stack.Push(nested);continue;}yield return next;}d.Player.SmokeWalk=Vector2.zero;d.Player.SmokeThrottle=0;for(int i=0;i<6;i++)PlayerPrefs.DeleteKey("SERVICE.test.result"+i);PlayerPrefs.DeleteKey("SERVICE.test.night");PlayerPrefs.Save();var result=(failed?"FAIL":"PASS")+": SERVICE_V5_SMOKE (five distinct properties, physical access and escape, friendly deliveries, pursuit and watcher rules, crouch/jump, live mirror, radio, scalable interface, retry checkpoint, surfaces, needle, pause, route save)";File.WriteAllText(Path.Combine(dir,"smoke-result.txt"),result);Debug.Log(result);Application.Quit(failed?1:0);}
  void Require(bool pass,string message){if(!pass)throw new Exception("SERVICE_V5: "+message);}
  IEnumerator Shot(string name){yield return null;yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Path.Combine(dir,name+".png"));yield return new WaitForSecondsRealtime(.2f);}
  IEnumerator Navigate(Vector3 target,bool sprint){
   Require(NavMesh.SamplePosition(d.Scene.Walker.transform.position,out var from,1.2f,NavMesh.AllAreas),"Start outside navigation");Require(NavMesh.SamplePosition(target,out var goal,1.2f,NavMesh.AllAreas),"Goal outside navigation");
   var path=new NavMeshPath();Require(NavMesh.CalculatePath(from.position,goal.position,NavMesh.AllAreas,path)&&path.status==NavMeshPathStatus.PathComplete,"No complete path to "+target);
   float start=Time.time;d.Player.SmokeSprint=sprint;
   foreach(var corner in path.corners){Debug.Log("V5_CORNER start="+d.Scene.Walker.transform.position+" target="+corner+" sprint="+sprint);float until=Time.time+35;while(Vector2.Distance(new Vector2(d.Scene.Walker.transform.position.x,d.Scene.Walker.transform.position.z),new Vector2(corner.x,corner.z))>.15f&&Time.time<until){if(sprint&&Vector3.Distance(d.Scene.View.transform.position,d.Scene.Car.position+Vector3.up)<3.2f){d.Player.SmokeWalk=Vector2.zero;d.Player.SmokeSprint=false;Debug.Log("V5_WALK escape seconds="+(Time.time-start));yield break;}Require(!d.Horror.Caught,"Caught during escape at property "+d.Horror.PropertyIndex+" position="+d.Scene.Walker.transform.position+" target="+corner+" elapsed="+(Time.time-start));d.Player.SmokeFace(corner);d.Player.SmokeWalk=Vector2.up;yield return null;}d.Player.SmokeWalk=Vector2.zero;Require(Time.time<until,"Physical route blocked: "+d.Scene.Walker.transform.position+" toward "+corner);}
   Require(Mathf.Abs(d.Scene.Walker.transform.position.y-goal.position.y)<.45f,"Wrong floor at "+target);Debug.Log("V5_WALK "+(sprint?"escape":"approach")+" seconds="+(Time.time-start));d.Player.SmokeSprint=false;
  }
  IEnumerator Check(){
   Require(AudioListener.volume==0,"Tests must start muted");
   Require(RenderSettings.fogDensity>=.025f&&RenderSettings.fogColor.b>.4f,"Reference fog applied at runtime");
   var thickets=d.Scene.transform.Find("Forest understory thickets");Require(thickets&&thickets.childCount>500,"Dense forest patches installed");
   Require(Resources.LoadAll<AudioClip>("Audio/V5/brush").Length>=6&&Resources.Load<AudioClip>("Audio/V5/insects/insects_0"),"Recorded forest variations installed");
   float introLimit=Time.realtimeSinceStartup+30;while(d.Presentation.IntroTextAlpha<.75f&&Time.realtimeSinceStartup<introLimit)yield return null;Require(d.Presentation.IntroVisible&&d.Presentation.IntroTextAlpha>.5f,"Headphone card fades in");yield return Shot("headphones");while(d.Presentation.IntroVisible&&Time.realtimeSinceStartup<introLimit)yield return null;Require(!d.Presentation.IntroVisible,"Headphone card fades out");
   var menuPosition=d.Scene.View.transform.position;yield return new WaitForSeconds(.7f);Require(Vector3.Distance(menuPosition,d.Scene.View.transform.position)>.001f,"Title camera moves");Require(d.Scene.Rain.isPlaying&&d.Scene.Rain.particleCount>0,"Rain renders on title");yield return Shot("00-title");d.HUD.SmokeOptions(true);yield return Shot("settings");Screen.SetResolution(960,720,false);yield return new WaitForSeconds(.8f);yield return Shot("settings-4x3");Screen.SetResolution(1280,720,false);yield return new WaitForSeconds(.8f);d.HUD.SmokeOptions(false);
   d.Storm.FlashesEnabled=true;d.Storm.TriggerLightning();yield return new WaitForSeconds(.05f);Require(d.Storm.FlashStrength>.1f,"Lightning illuminates scene");yield return Shot("manor-lightning");yield return new WaitForSeconds(.8f);Require(d.Storm.FlashStrength==0,"Lightning recovers");
   d.BeginShift(0);Require(d.Docket.Count==5,"First shift needs five stops");Require(d.Docket.Select(e=>d.Property(e.Property).Template).Distinct().Count()==5,"Repeated building template");yield return Shot("01-docket");d.MapOpen=true;yield return Shot("02-map");Require(d.HUD.MapPins==5&&d.HUD.MapSegments>20,"Map contains every stop and actual curved road");d.ToggleDocument(true);Require(!d.PaperOpen,"M closes map");d.ToggleDocument(true);Require(d.PaperOpen&&d.MapOpen,"M opens map");d.ToggleDocument(false);Require(d.PaperOpen&&!d.MapOpen,"Tab changes map to docket");d.ToggleDocument(false);Require(!d.PaperOpen,"Tab closes docket");
   d.Player.StartEngine();yield return new WaitForSeconds(.8f);d.Player.SmokeThrottle=1;yield return new WaitForSeconds(2);d.Player.SmokeThrottle=0;Require(d.Player.Speed>1,"Car moves");var needle=d.Scene.SpeedNeedle.up;var axis=d.Scene.SpeedNeedle.parent;float angle=Mathf.Lerp(220,-40,d.Player.Speed*2.237f/60)*Mathf.Deg2Rad;Require(Vector3.Dot(needle,axis.TransformDirection(new Vector3(Mathf.Cos(angle),Mathf.Sin(angle),0)))>.98f,"Speed needle follows dial");d.Player.StopEngine();d.Player.SmokeLook(0,24);yield return new WaitForSeconds(.5f);yield return Shot("03-cockpit");
   Require(d.Vehicle.StationsAvailable&&d.Vehicle.MirrorLive,"Radio tracks and live rearview camera");d.Vehicle.ToggleRadio();Require(d.Vehicle.RadioOn,"Radio power");d.Vehicle.NextStation();Require(d.Vehicle.Station==1,"Radio tuning");yield return Shot("radio");d.Player.SmokeLook(0,-12);yield return new WaitForSeconds(.5f);yield return Shot("rearview");d.Vehicle.ToggleRadio();
   Require(Resources.LoadAll<AudioClip>("Audio/V5/grass").Length>4&&Resources.LoadAll<AudioClip>("Audio/V5/wood").Length>4,"Footstep variations");
   var first=d.Property(0);d.Player.SmokePlaceWalker(first.ApproachRoute[4]);d.Player.SmokeFace(first.ApproachRoute[10]);yield return new WaitForSeconds(.3f);d.Player.SmokeCrouch=true;yield return new WaitForSeconds(.3f);Require(d.Player.Crouched&&d.Scene.Walker.height<1.2f,"Ctrl crouches");var ceiling=GameObject.CreatePrimitive(PrimitiveType.Cube);ceiling.name="Smoke headroom blocker";ceiling.transform.position=d.Scene.Walker.transform.position+Vector3.up*1.5f;ceiling.transform.localScale=new Vector3(2,.15f,2);Physics.SyncTransforms();d.Player.SmokeCrouch=false;yield return new WaitForSeconds(.2f);Require(d.Player.Crouched,"Ceiling prevents standing");Destroy(ceiling);yield return new WaitForSeconds(.3f);Require(!d.Player.Crouched,"Clear headroom restores standing");float ground=d.Scene.Walker.transform.position.y;d.Player.SmokeJump=true;yield return new WaitForSeconds(.22f);Require(d.Scene.Walker.transform.position.y>ground+.3f,"Jump leaves the ground");yield return new WaitForSeconds(.8f);Require(Mathf.Abs(d.Scene.Walker.transform.position.y-ground)<.15f,"Jump lands on ground");var forward=d.Scene.Walker.transform.forward;var origin=d.Scene.Walker.transform.position;
   d.Player.SmokeSprint=true;d.Player.SmokeWalk=Vector2.up;d.Player.SmokeLookBack=-1;yield return new WaitForSeconds(.4f);
   Require(Vector3.Dot(d.Scene.Walker.transform.forward,forward)>.99f&&Vector3.Dot(d.Scene.Walker.transform.position-origin,forward)>1,"Looking back preserves forward running");Require(Vector3.Dot(d.Scene.View.transform.forward,forward)<-.8f&&d.Player.InteractionSuppressed,"Q sees behind without interaction");yield return Shot("look-back-left");
   d.Player.SmokeLookBack=1;yield return new WaitForSeconds(.5f);Require(d.Player.LookBackAngle>150,"E looks over right shoulder");d.Player.SmokeLookBack=0;d.Player.SmokeWalk=Vector2.zero;d.Player.SmokeSprint=false;yield return new WaitForSeconds(.4f);Require(Mathf.Abs(d.Player.LookBackAngle)<1&&!d.Player.InteractionSuppressed,"Release restores forward view and interaction");
   var zone=d.Scene.transform.Find("Storm verge planting").GetComponentInChildren<ServiceBrushZone>();Require(zone&&ServiceBrushZone.Active.Count>100,"Bush contact zones exist");d.Player.SmokePlaceWalker(zone.Center);d.Player.SmokeFace(zone.Center+Vector3.right*3);yield return new WaitForSeconds(1.1f);int brushCount=d.Audio.BrushEvents;d.Player.SmokeWalk=Vector2.up;yield return new WaitForSeconds(.22f);d.Player.SmokeWalk=Vector2.zero;Require(d.Audio.BrushEvents>brushCount,"Walking through bushes rustles");
   d.Audio.Footstep(d.Scene.Walker.transform.position);Require(d.Audio.LastFootstepPool.StartsWith("wet"),"Exposed footsteps use wet recordings");
   foreach(int index in new[]{0,3,1,4,5}){
    Require(AudioListener.volume==0,"Tests must remain muted");
    var p=d.Property(index);d.Player.TeleportCar(p.Gate.position-p.Gate.forward*3,Quaternion.LookRotation(p.Gate.forward));if(index==0){d.Player.EnterCar();yield return new WaitForSeconds(.4f);var prior=RenderTexture.active;RenderTexture.active=d.Vehicle.MirrorTexture;var texture=new Texture2D(768,192,TextureFormat.RGB24,false);texture.ReadPixels(new Rect(0,0,768,192),0,0);texture.Apply();File.WriteAllBytes(Path.Combine(dir,"mirror-feed.png"),texture.EncodeToPNG());Destroy(texture);RenderTexture.active=prior;}d.Player.SmokePlaceWalker(p.Gate.position);d.Player.SmokeFace(p.Door.position);yield return Shot("property-"+index+"-approach");
    if(index==0){yield return Navigate(p.ApproachRoute[p.ApproachRoute.Length/2],false);d.Player.SmokeFace(p.Door.position+Vector3.up);yield return Shot("forest-reference");if(d.Scene.transform.Find("Scanned woodland details")){d.Player.SmokeLook(d.Scene.Walker.transform.eulerAngles.y,25);yield return Shot("woodland-ground");d.Player.SmokeLook(d.Scene.Walker.transform.eulerAngles.y-65,12);yield return Shot("woodland-verge");d.Player.SmokeFace(p.Door.position);float seconds=0;for(int f=0;f<120;f++){yield return null;seconds+=Time.unscaledDeltaTime;}File.WriteAllText(Path.Combine(dir,"frame-sample.txt"),"120 stationary forest frames: "+(120/seconds).ToString("F1")+" FPS. Not a full performance benchmark.");}}
    if(index==3){yield return Navigate(p.Door.position+p.Door.forward*1.2f,false);d.Player.SmokeFace(p.Door.position);d.Attempt(index,ServiceResult.Served);yield return new WaitForSeconds(2.3f);Require(!d.Busy&&!d.Horror.Active,"Knock opens hostile entrance without prematurely starting chase");yield return Shot("harrow-door");}
    if(!d.IsFriendly(index)){yield return Navigate(p.TableApproach.position,false);Require(d.NearbyDoor()==index,"Delivery unavailable at property "+index);Require(d.Audio.SurfaceAt(d.Scene.Walker.transform.position)=="wood","Interior wood surface "+index);d.Audio.Footstep(d.Scene.Walker.transform.position);Require(d.Audio.LastFootstepPool=="wood","Sheltered interior footsteps stay dry");yield return new WaitForSeconds(.15f);Require(!d.Scene.Rain.isPlaying,"Rain stays outside interiors");d.Player.SmokeFace(p.DeliveryPoint.position);yield return Shot("property-"+index+"-interior");}if(d.IsFriendly(index)){
     yield return Navigate(p.Door.position+p.Door.forward*1.2f,false);d.Player.SmokeFace(p.Door.position+Vector3.up);yield return new WaitForSeconds(.2f);Require(d.NearbyKnockDoor()==index,"Front door knock available");yield return Shot("property-"+index+"-door");int knocks=d.KnockCount;d.Attempt(index,ServiceResult.Served);Require(d.Busy&&d.KnockCount==knocks+1,"Knocking starts");yield return new WaitForSeconds(3.3f);Require(d.ResultAt(index)==ServiceResult.Served&&!d.Horror.Active,"Friendly delivery accepted without threat");yield return Shot("property-"+index+"-presence");
     if(index==0){Require(d.Life.DogPresent&&d.Life.DogTravel>.1f,"Authored yard dog moves");var dog=d.Scene.transform.Find("Correll yard dog");d.Player.SmokePlaceWalker(dog.position+p.Door.forward*3);d.Player.SmokeFace(dog.position+Vector3.up*.45f);yield return null;d.Player.SmokeLook(d.Scene.Walker.transform.eulerAngles.y,20);d.Scene.Flashlight.enabled=true;d.Life.Bark();yield return new WaitForSeconds(.5f);yield return Shot("yard-dog");d.Scene.Flashlight.enabled=false;}
     d.Player.EnterCar();continue;
    }
    d.Attempt(index,ServiceResult.LeftAtDoor);Require(d.Horror.Active&&d.Horror.PropertyIndex==index,"Encounter did not start "+index);
    d.Pause();if(index==1)yield return Shot("pause");float elapsed=d.Horror.Elapsed;yield return new WaitForSecondsRealtime(.15f);Require(AudioListener.pause&&Mathf.Abs(elapsed-d.Horror.Elapsed)<.01f,"Pause freezes audio and encounter");d.Resume();
    if(index==3){
     Require(p.CreatureVariant==3 && d.Scene.EntityVariants.Length==4,"Distinct Demon variant installed"); d.Player.SmokeFace(d.Horror.Agent.transform.position); yield return Shot("watcher-presence");
     yield return new WaitForSeconds(1.2f);d.Player.SmokeWalk=Vector2.up;d.Player.SmokeSprint=true;yield return new WaitForSeconds(.25f);d.Player.SmokeWalk=Vector2.zero;d.Player.SmokeSprint=false;Require(d.Horror.Caught,"Running must fail watcher");yield return Shot("watcher-failure");yield return new WaitForSeconds(4);Require(d.ResultAt(0)!=ServiceResult.Pending&&d.ResultAt(3)==ServiceResult.Pending,"Retry preserves other deliveries");
     yield return Navigate(p.TableApproach.position,false);d.Attempt(index,ServiceResult.LeftAtDoor);d.Player.SmokeFace(d.Scene.Walker.transform.position+(d.Scene.Walker.transform.position-d.Horror.Agent.transform.position));yield return new WaitForSeconds(9.6f);Require(d.Horror.Phase==PursuitPhase.Escaped,"Look away eight seconds must dismiss watcher");yield return Shot("watcher-dismissed");d.Player.EnterCar();
    }else{
     d.Player.SmokeFace(d.Horror.Agent.transform.position);yield return new WaitForSeconds(3.3f);Require(d.Horror.Phase==PursuitPhase.Chase,"Pursuit starts "+index);Require(d.Audio.ChaseLevel>.1f,"Chase music rises");yield return Shot("property-"+index+"-presence");yield return Navigate(p.Gate.position-p.Gate.forward*2,true);Require(d.Horror.Active,"Must escape alive "+index);Require(Vector3.Distance(d.Scene.View.transform.position,d.Scene.Car.position+Vector3.up)<3.5f,"Reach car interaction "+index);d.Player.EnterCar();yield return null;Require(d.Horror.Phase==PursuitPhase.Escaped,"Car escape "+index);
    }
   }
   Require(d.AllResolved,"All five notices resolved");d.Player.TeleportCar(d.Scene.Depot.position,Quaternion.identity);Require(d.TryFinishShift(),"File five-stop report");yield return Shot("09-report");d.Title();Require(d.HasSavedRoute,"Route saved");d.ContinueRoute();Require(d.NightIndex==1&&d.Docket.Count==5,"Saved second shift");d.MapOpen=true;yield return Shot("second-shift-map");Require(d.HUD.MapPins==5,"Second shift map retains all stops");d.BeginShift(2);d.MapOpen=true;yield return Shot("third-shift-map");Require(d.HUD.MapPins==2,"Third shift map uses current docket");d.BeginShift(0);Require(d.Horror.Phase==PursuitPhase.Dormant,"Restart resets encounters");
  }
 }
}
