using System;using System.IO;using System.Linq;using System.Collections;using System.Collections.Generic;using UnityEngine;using UnityEngine.AI;
namespace ServiceGameV2 {public sealed class ServiceV16Smoke:MonoBehaviour {
 ServiceDirector d;string dir;List<string> checks=new List<string>();
 public void Run(ServiceDirector director){d=director;dir=Environment.GetEnvironmentVariable("SERVICE_CAPTURE_DIR");Directory.CreateDirectory(dir);StartCoroutine(Guard());}
 IEnumerator Guard(){var stack=new Stack<IEnumerator>();stack.Push(Check());bool failed=false;while(stack.Count>0){object next=null;bool more=false;try{more=stack.Peek().MoveNext();if(more)next=stack.Peek().Current;}catch(Exception e){Debug.LogException(e);checks.Add("FAIL "+e.Message);failed=true;break;}if(!more){stack.Pop();continue;}if(next is IEnumerator nested)stack.Push(nested);else yield return next;}File.WriteAllLines(Path.Combine(dir,"results.txt"),new[]{failed||checks.Any(c=>c.StartsWith("FAIL"))?"FAIL":"PASS"}.Concat(checks));Application.Quit(failed?1:0);}
 void Require(bool ok,string message){if(!ok)throw new Exception(message);checks.Add("PASS "+message);File.WriteAllLines(Path.Combine(dir,"progress.txt"),checks);}
 IEnumerator Face(Vector3 target){var delta=target-d.Scene.View.transform.position;float yaw=Mathf.Atan2(delta.x,delta.z)*Mathf.Rad2Deg;float pitch=-Mathf.Atan2(delta.y,new Vector2(delta.x,delta.z).magnitude)*Mathf.Rad2Deg;d.Player.SmokeLook(yaw,pitch);yield return new WaitForSeconds(.25f);}
 IEnumerator Shot(string name){yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Path.Combine(dir,name+".png"));yield return new WaitForSeconds(.2f);}
 IEnumerator Walk(Vector3 target){Require(NavMesh.SamplePosition(d.Scene.Walker.transform.position,out var from,2,NavMesh.AllAreas),"Navigation start");Require(NavMesh.SamplePosition(target,out var to,2,NavMesh.AllAreas),"Navigation goal");var path=new NavMeshPath();Require(NavMesh.CalculatePath(from.position,to.position,NavMesh.AllAreas,path)&&path.status==NavMeshPathStatus.PathComplete,"Connected route to "+target);foreach(var corner in path.corners){float timeout=Time.time+20;while(Vector2.Distance(new Vector2(d.Scene.Walker.transform.position.x,d.Scene.Walker.transform.position.z),new Vector2(corner.x,corner.z))>.2f){if(Time.time>timeout)throw new Exception("Physical obstruction "+d.Scene.Walker.transform.position+" toward "+corner);d.Player.SmokeFace(corner);d.Player.SmokeWalk=Vector2.up;yield return null;}d.Player.SmokeWalk=Vector2.zero;}yield return new WaitForSeconds(.2f);}
 IEnumerator Check(){yield return new WaitForSeconds(1);d.BeginShift(0);d.PaperOpen=false;
  var residents=d.Scene.GetComponentInChildren<ServiceResidents>();var worker=residents.DepotWorker;d.Player.SmokePlaceWalker(worker.position+Vector3.forward*4);yield return Face(worker.position+Vector3.up*1.5f);yield return new WaitForSeconds(.6f);yield return Shot("depot-worker");var motionRoot=worker.GetComponentsInChildren<Transform>().First(t=>t.name.EndsWith("walking_root"));float min=999,max=-999;float until=Time.time+3;while(Time.time<until){min=Mathf.Min(min,motionRoot.localPosition.z);max=Mathf.Max(max,motionRoot.localPosition.z);yield return null;}Require(max-min<.1f,"NPC walking cycle does not reset forward position");yield return Face(worker.position+Vector3.up*1.5f);yield return Shot("depot-worker-close");
  Require(d.Docket.All(e=>!e.Case.Contains("Upstairs")&&!e.Case.Contains("gallery")),"No undiscovered room directions in docket");
  Require(d.Scene.View.GetComponentInChildren<ServiceHands>()!=null,"Authored hands installed");Require(d.Scene.GetComponentInChildren<ServiceResidents>()!=null,"Residents installed");
  foreach(int index in new[]{0,1,3,4,5}){
   d.BeginShift(0);d.PaperOpen=false;var p=d.Property(index);d.Player.SmokePlaceWalker(p.Door.position+p.Door.forward*1.75f);yield return new WaitForSeconds(.3f);yield return Face(p.KnockPoint.position);
   Require(p.DoorPanel&&p.KnockPoint,"Real door at property "+index);Require(d.NearbyKnockDoor()==index,"Can knock on visible door "+index);yield return Shot(index+"-front-door");
   yield return Face(d.Scene.View.transform.position+p.Door.forward*4);Require(d.NearbyKnockDoor()!=index,"No knock while facing away "+index);yield return Face(p.KnockPoint.position);
   d.Attempt(index,ServiceResult.Served);yield return new WaitForSeconds(.17f);if(index==0){Require(d.Scene.View.GetComponentInChildren<ServiceHands>().GetComponentsInChildren<Renderer>().Any(r=>r.enabled),"Hands visible during knock");yield return Shot("hands-knocking");}yield return new WaitForSeconds(2.1f);yield return Shot(index+"-door-open-resident");yield return new WaitForSeconds(1.2f);Require(d.AccessGranted(index),"Knock grants access "+index);
   if(!d.IsFriendly(index)){yield return Walk(p.TableApproach.position);yield return Face(p.DeliveryPoint.position);yield return Shot(index+"-delivery-room");if(d.NearbyDoor()!=index){var from=d.Scene.View.transform.position;var to=p.DeliveryPoint.position+Vector3.up*.09f;Debug.Log("V16_TABLE "+index+" camera="+from+" target="+to+" forward="+d.Scene.View.transform.forward+" access="+d.AccessGranted(index)+" result="+d.ResultAt(index));foreach(var hit in Physics.RaycastAll(from,(to-from).normalized,Vector3.Distance(from,to),~0,QueryTriggerInteraction.Ignore))Debug.Log("V16_HIT "+hit.transform.name+" layer="+hit.transform.gameObject.layer+" distance="+hit.distance);checks.Add("FAIL Reachable table "+index);}else Require(true,"Reachable delivery table "+index);}
  }
  var watcher=d.Property(3);d.BeginShift(0);d.PaperOpen=false;d.Player.SmokePlaceWalker(watcher.TableApproach.position);yield return null;d.Horror.Begin(3);yield return new WaitForSeconds(.2f);yield return Face(d.Horror.Agent.transform.position+Vector3.up*1.15f);yield return new WaitForSeconds(2.5f);Require(d.Horror.Caught,"Standing still while staring triggers watcher attack");yield return Shot("watcher-staring-attack");yield return new WaitForSeconds(5);Require(d.AccessGranted(3)&&d.ResultAt(3)==ServiceResult.Pending,"Watcher retry retains unlocked door");
  d.Player.SmokePlaceWalker(watcher.TableApproach.position);yield return null;d.Horror.Begin(3);yield return null;var away=d.Scene.View.transform.position-(d.Horror.Agent.transform.position-d.Scene.View.transform.position);yield return Face(away);yield return new WaitForSeconds(9.2f);Require(!d.Horror.Caught&&!d.Horror.Active,"Still and looking away safely ends encounter");yield return Shot("watcher-look-away-success");
  d.Horror.ResetEncounter();d.Player.SmokePlaceWalker(watcher.TableApproach.position);yield return null;d.Horror.Begin(3);yield return Face(away);yield return new WaitForSeconds(1.2f);d.Player.SmokeWalk=Vector2.up;yield return new WaitForSeconds(.4f);d.Player.SmokeWalk=Vector2.zero;Require(d.Horror.Caught,"Walking without sprint still triggers watcher");d.Horror.ResetEncounter();
  foreach(float side in new[]{-32f,9f}){d.BeginShift(0);d.PaperOpen=false;foreach(var entry in d.Docket)entry.Result=ServiceResult.Served;d.Player.TeleportCar(new Vector3(side,.08f,0),Quaternion.identity);d.Player.EnterCar();d.Player.StopEngine();yield return null;Require(d.CanFinish,"Can report from depot shoulder x="+side);Require(d.TryFinishShift(),"Report accepted x="+side);}
  foreach(int index in new[]{0,1,3,4,5}){d.BeginShift(0);d.PaperOpen=false;var p0=d.Property(index);d.Player.SmokePlaceWalker(p0.NoticePoint.position+p0.Door.forward*1.6f-Vector3.up*1.7f);yield return new WaitForSeconds(.4f);yield return Face(p0.NoticePoint.position);Require(d.NearbyNotice()==index,"Local notice readable "+index);d.ReadNotice(index);Require(d.NoticeRead(index),"Notice discovery recorded "+index);yield return Shot("local-notice-"+index);}
  var profile=d.Scene.GetComponentInChildren<UnityEngine.Rendering.Volume>().profile;Require(profile.TryGet<UnityEngine.Rendering.Universal.FilmGrain>(out var grain)&&grain.intensity.value>.1f,"Grain persisted and loaded in player");

 }
}}
