using System;
using System.IO;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.AI;
namespace ServiceGameV2 {
 public sealed class ServiceV4Smoke:MonoBehaviour {
 ServiceDirector d;string dir;
 public void Run(ServiceDirector director){d=director;dir=Environment.GetEnvironmentVariable("SERVICE_CAPTURE_DIR");if(string.IsNullOrEmpty(dir))dir=Path.Combine(Application.persistentDataPath,"SmokeV4");Directory.CreateDirectory(dir);StartCoroutine(Guard());}
 IEnumerator Guard(){var stack=new Stack<IEnumerator>();stack.Push(Check());bool failed=false;while(stack.Count>0){object next=null;bool more=false;try{more=stack.Peek().MoveNext();if(more)next=stack.Peek().Current;}catch(Exception e){Debug.LogException(e);failed=true;break;}if(!more){stack.Pop();continue;}if(next is IEnumerator nested){stack.Push(nested);continue;}yield return next;}d.Player.SmokeWalk=Vector2.zero;d.Player.SmokeThrottle=0;string result=failed?"FAIL: SERVICE_V4_SMOKE":"PASS: SERVICE_V4_SMOKE (vehicle movement, cabin approach, physical villa entry, table placement, animated entity navigation, capture checkpoint, sprint escape, all three shifts and reports, restart, captures)";PlayerPrefs.DeleteKey("SERVICE.test.night");for(int i=0;i<3;i++)PlayerPrefs.DeleteKey("SERVICE.test.result"+i);PlayerPrefs.Save();File.WriteAllText(Path.Combine(dir,"smoke-result.txt"),result);Debug.Log(result);Application.Quit(failed?1:0);}
 void Require(bool yes,string message){if(!yes)throw new Exception("SERVICE_V4: "+message);}
 IEnumerator Shot(string name){yield return null;yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Path.Combine(dir,name+".png"));yield return new WaitForSeconds(.25f);}
 IEnumerator WalkTo(Vector3 target,bool sprint,float limit=14){d.Player.SmokeSprint=sprint;float end=Time.time+limit;while(Vector3.Distance(new Vector3(d.Scene.Walker.transform.position.x,target.y,d.Scene.Walker.transform.position.z),target)>.12f&&Time.time<end){d.Player.SmokeFace(target);d.Player.SmokeWalk=Vector2.up;yield return null;}d.Player.SmokeWalk=Vector2.zero;Require(Time.time<end,"Physical walking blocked toward "+target+" from "+d.Scene.Walker.transform.position);}
 IEnumerator Navigate(Vector3 target,bool sprint){
  Require(NavMesh.SamplePosition(d.Scene.Walker.transform.position,out var from,1,NavMesh.AllAreas),"Walker navigation start");
  var path=new NavMeshPath();Require(NavMesh.CalculatePath(from.position,target,NavMesh.AllAreas,path)&&path.status==NavMeshPathStatus.PathComplete,"Continuous stairs route to "+target);
  float start=Time.time;bool stairsShot=false;foreach(var corner in path.corners){yield return WalkTo(corner,sprint,10);if(!sprint&&!stairsShot&&d.Scene.Walker.transform.position.y>2){stairsShot=true;yield return Shot("02-stairwell");}}
  Require(Mathf.Abs(d.Scene.Walker.transform.position.y-target.y)<.4f,"Must physically reach correct floor");
  Debug.Log("STAIRS_ROUTE "+(sprint?"escape":"approach")+" seconds="+(Time.time-start)+" y="+d.Scene.Walker.transform.position.y);
  if(!sprint){d.Player.SmokeFace(d.Property(1).DeliveryPoint.position);yield return Shot("04-upstairs");}
 }
 IEnumerator Check(){
  yield return null;yield return Shot("00-title");var hud=d.GetComponent<ServiceHUD>();hud.SmokeOptions(true);yield return Shot("00-options");hud.SmokeOptions(false);d.BeginShift(0);Require(d.Docket.Count==2&&d.Player.InCar,"Initial docket");yield return Shot("01-docket");d.MapOpen=true;yield return Shot("01-map");d.MapOpen=false;d.PaperOpen=false;
  d.Player.SmokeLook(-75,12);yield return Shot("00-car-left");d.Player.SmokeLook(75,12);yield return Shot("00-car-right");d.Player.SmokeLook(0,28);yield return Shot("00-car-instruments");d.Player.SmokeLook(0,0);
  yield return Shot("00-driving");var carStart=d.Scene.Car.position;d.Player.SmokeThrottle=1;yield return new WaitForSeconds(2);d.Player.SmokeThrottle=0;Require(Vector3.Distance(carStart,d.Scene.Car.position)>1,"Car must physically drive");
  var cabin=d.Property(0);d.Player.TeleportCar(cabin.Gate.position+cabin.Door.forward*4,Quaternion.identity);Require(d.Player.TryExitCar(),"Cabin parking exit");d.Player.SmokePlaceWalker(cabin.Gate.position);yield return WalkTo(cabin.Door.position+cabin.Door.forward*1.1f,false);Require(d.NearbyDoor()==0,"Cabin door interaction");yield return Shot("01a-threshold");d.Attempt(0,ServiceResult.Served);yield return new WaitForSeconds(3.4f);Require(d.ResultAt(0)==ServiceResult.Served,"First delivery");
  var p=d.Property(1);d.Player.EnterCar();d.Player.TeleportCar(p.Gate.position+p.Door.forward*3,Quaternion.LookRotation(-p.Door.forward));Require(d.Player.TryExitCar(),"Villa car exit");d.Player.SmokePlaceWalker(p.Gate.position);d.Player.SmokeFace(p.Door.position);yield return Shot("02-property");
  d.Attempt(1,ServiceResult.LeftAtDoor);Require(d.ResultAt(1)==ServiceResult.Pending,"Cannot deliver at exterior gate");
  yield return Navigate(p.TableApproach.position,false);Require(d.NearbyDoor()==1,"Indoor table must be reachable");Require(d.Scene.Walker.transform.position.y>4f,"Officer must stand on villa floor");d.Scene.View.transform.LookAt(p.DeliveryPoint.position);yield return Shot("04-table");
  var path=new NavMeshPath();Require(NavMesh.CalculatePath(p.EntitySpawn.position,p.Gate.position,NavMesh.AllAreas,path)&&path.status==NavMeshPathStatus.PathComplete,"Entity path must connect room and driveway");
  d.Attempt(1,ServiceResult.Served);Require(d.Horror.Phase==PursuitPhase.Reveal&&p.PostedPaper.activeSelf,"Table placement must trigger reveal");Require(!p.WindowLight.enabled,"Reveal switches hall light off");d.Player.SmokeFace(p.EntitySpawn.position);yield return Shot("05-reveal");
  var entityStart=d.Horror.Agent.transform.position;float held=d.Horror.Elapsed;d.Pause();yield return new WaitForSecondsRealtime(.25f);Require(AudioListener.pause&&Mathf.Abs(d.Horror.Elapsed-held)<.02f,"Pause must freeze pursuit and sound");d.Resume();yield return null;Require(!AudioListener.pause,"Resume sound");yield return new WaitForSeconds(4.0f);Require(d.Horror.Phase==PursuitPhase.Chase,"Reveal must transition to chase");Require(Vector3.Distance(entityStart,d.Horror.Agent.transform.position)>.4f,"Entity must move using navigation");Require(d.Scene.Entity.GetComponentInChildren<Animator>().GetCurrentAnimatorStateInfo(0).normalizedTime>.1f,"Authored creature animation must play");yield return Shot("06-chase");
  float deadline=Time.time+24;while(!d.Horror.Caught&&Time.time<deadline)yield return null;Require(d.Horror.Caught,"Approaching creature must catch a stationary officer");yield return Shot("07-caught");yield return new WaitForSeconds(2.7f);Require(d.Horror.Captures==1&&d.Horror.Phase==PursuitPhase.Dormant,"Capture checkpoint reset");Require(d.ResultAt(0)==ServiceResult.Served&&d.ResultAt(1)==ServiceResult.Pending,"Checkpoint preserves prior delivery");
  yield return Navigate(p.TableApproach.position,false);d.Attempt(1,ServiceResult.LeftAtDoor);yield return new WaitForSeconds(3.3f);yield return Navigate(p.Gate.position,true);d.Player.SmokeSprint=false;Require(Vector3.Distance(d.Scene.View.transform.position,d.Scene.Car.position+Vector3.up)<3.5f,"Sprint must reach actual car entry");Require(d.Horror.Active,"Sprint escape must beat creature");d.Player.EnterCar();yield return null;Require(d.Horror.Phase==PursuitPhase.Escaped,"Car is safe");yield return Shot("08-escape");
  d.Player.TeleportCar(d.Scene.Depot.position,Quaternion.identity);Require(d.TryFinishShift(),"First report");d.Title();Require(d.HasSavedRoute,"Filed route must be saved");d.ContinueRoute();Require(d.NightIndex==1,"Saved second shift");d.PaperOpen=false;d.Player.SmokePlaceWalker(p.Gate.position);d.Scene.View.transform.rotation=Quaternion.LookRotation(d.Scene.View.transform.position-p.Door.position);bool was=p.PorchLight.enabled;d.SmokeAdvanceCues(30);Require(was!=p.PorchLight.enabled&&d.Player.IgnitionDelayPending,"Second-night cues");d.Attempt(0,ServiceResult.Unable);d.Attempt(1,ServiceResult.Unable);d.Player.EnterCar();d.Player.StartEngine();Require(d.Player.IsStarting&&!d.Player.EngineRunning,"Delayed ignition");yield return new WaitForSeconds(5);Require(d.Player.EngineRunning,"Ignition recovers");d.Player.TeleportCar(d.Scene.Depot.position,Quaternion.identity);Require(d.TryFinishShift(),"Second report");d.NextShift();
  d.PaperOpen=false;d.Player.TeleportCar(d.Scene.LateThreshold.position+d.Scene.LateThreshold.forward*12,Quaternion.identity);yield return null;Require(d.OdometerFrozen&&d.Scene.LateRoad.activeSelf,"Final survey boundary");d.Attempt(1,ServiceResult.Unable);d.Attempt(2,ServiceResult.LeftAtDoor);d.Player.TeleportCar(d.Scene.Depot.position,Quaternion.identity);Require(d.TryFinishShift(),"Final report");yield return Shot("03-report");d.BeginShift(0);Require(d.Horror.Phase==PursuitPhase.Dormant&&!d.Scene.Entity.activeSelf,"Replay resets encounter");d.RequestEarlyFinish();Require(d.TryFinishShift(),"Early report");
 }
 }
}



