using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Object=UnityEngine.Object;
namespace ServiceGameV2.Editor {public static class ServiceV16Finish {
 public static void Run(){
  var s=ServiceV16Audit.Open();const string path="Assets/External/DrillimpactArms/Arms-metres.fbx";var importer=(ModelImporter)AssetImporter.GetAtPath(path);importer.animationType=ModelImporterAnimationType.Legacy;importer.globalScale=1;importer.isReadable=true;importer.importCameras=false;importer.importLights=false;importer.SaveAndReimport();
  var hands=s.View.GetComponentInChildren<ServiceHands>();foreach(Transform t in hands.transform.Cast<Transform>().ToArray())Object.DestroyImmediate(t.gameObject);hands.transform.localRotation=Quaternion.identity;hands.transform.localPosition=new Vector3(0,-1.74315f,.28f);
  var model=Object.Instantiate(AssetDatabase.LoadAssetAtPath<GameObject>(path),hands.transform);model.transform.localPosition=Vector3.zero;model.transform.localRotation=Quaternion.identity;model.transform.localScale=Vector3.one;hands.Rig=model.GetComponent<Animation>();var clips=AssetDatabase.LoadAllAssetsAtPath(path).OfType<AnimationClip>().Where(c=>!c.name.StartsWith("__")).ToArray();var idle=clips.First(c=>c.name.EndsWith("|relax")||c.name=="relax");hands.Rig.clip=idle;hands.Rig.playAutomatically=true;foreach(AnimationState state in hands.Rig)state.wrapMode=WrapMode.Loop;idle.SampleAnimation(model,0);
  foreach(var r in model.GetComponentsInChildren<SkinnedMeshRenderer>()){r.sharedMaterial=AssetDatabase.LoadAssetAtPath<Material>("Assets/ServiceArt/V16 Drillimpact hands.mat");r.enabled=true;r.shadowCastingMode=UnityEngine.Rendering.ShadowCastingMode.Off;r.updateWhenOffscreen=false;r.localBounds=new Bounds(Vector3.zero,Vector3.one*8);}
  var harrow=s.Properties.Single(p=>p.Index==3);var before=harrow.DeliveryPoint.position;var delta=new Vector3(88.5f,before.y,156.4f)-before;
  foreach(Transform t in harrow.transform.Cast<Transform>().Where(t=>t.name.StartsWith("Prop_SmallTable_B")||t.name.StartsWith("Prop_Lamp_A")).ToArray())if(Vector3.Distance(t.position,before)<3)t.position+=delta;
  harrow.DeliveryPoint.position+=delta;harrow.TableApproach.position=new Vector3(87.25f,.78f,156.4f);if(harrow.PostedPaper)harrow.PostedPaper.transform.position+=delta;harrow.EntitySpawn.position=new Vector3(82.9f,.78f,153.4f);
  harrow.Instructions="The delivery table is at the far end of the hall, beside the lamp.";harrow.NoticeText="DELIVERIES\nPlease leave documents on the table beside the lamp\nat the far end of the hall.\nIf you hear breathing: turn away. Stay still.";
  // Replace selected existing bare silhouettes with the authored conifer variant.
  // These are fixed composition points, not a random planting/scenery generator.
  var points=new[]{new Vector2(-48,20),new Vector2(-42,40),new Vector2(21,37),new Vector2(22,64),new Vector2(-44,75),new Vector2(-78,72),new Vector2(-86,91),new Vector2(-80,112),new Vector2(-48,117),new Vector2(37,125),new Vector2(65,129),new Vector2(95,140),new Vector2(96,164),new Vector2(65,169),new Vector2(53,193),new Vector2(65,212),new Vector2(118,211),new Vector2(122,241),new Vector2(74,251),new Vector2(-46,258),new Vector2(-60,276),new Vector2(-96,286),new Vector2(-95,320),new Vector2(-59,326),new Vector2(24,329),new Vector2(60,339),new Vector2(107,341),new Vector2(105,383),new Vector2(55,386),new Vector2(-17,366),new Vector2(-52,370),new Vector2(-48,341),new Vector2(-48,220),new Vector2(-48,178),new Vector2(-48,142),new Vector2(19,18)};
  var trees=s.GetComponentsInChildren<Transform>().Where(t=>t.name=="PF Conifer Bare BOTD URP").ToList();var source=s.GetComponentsInChildren<Transform>().First(t=>t.name=="PF Conifer Medium BOTD URP");var terrain=s.GetComponentInChildren<Terrain>();int replaced=0;
  foreach(var point in points){var old=trees.OrderBy(t=>Vector2.Distance(point,new Vector2(t.position.x,t.position.z))).FirstOrDefault();if(!old||Vector2.Distance(point,new Vector2(old.position.x,old.position.z))>14)continue;trees.Remove(old);var o=Object.Instantiate(source.gameObject,old.parent);o.name="V16 retained woodland conifer";o.transform.position=old.position;o.transform.rotation=old.rotation;o.transform.localScale=Vector3.one*1.1f;o.transform.position=new Vector3(old.position.x,terrain.SampleHeight(old.position)+terrain.transform.position.y-.18f,old.position.z);Object.DestroyImmediate(old.gameObject);replaced++;}
  // Stop stretching one texture over the entire 396 metre return segment.
  var road=s.GetComponentInChildren<ServiceReturnRoad>();int id=0;foreach(var t in road.transform.Cast<Transform>().Where(t=>t.name=="road-straight"||t.name.StartsWith("V16 joined"))){var original=s.transform.Find("Millbrook and Latigo").GetComponent<Renderer>().sharedMaterial;string matPath="Assets/ServiceArt/V16 return surface "+id+++".mat";var mat=new Material(original);mat.SetTextureScale("_BaseMap",new Vector2(t.localScale.x/4,t.localScale.z/4));mat.SetTextureScale("_BumpMap",new Vector2(t.localScale.x/4,t.localScale.z/4));AssetDatabase.CreateAsset(mat,matPath);foreach(var r in t.GetComponentsInChildren<Renderer>())r.sharedMaterial=mat;}
  File.WriteAllText(Path.Combine(ServiceV16Audit.Work,"v16-finish.txt"),"Retained tree positions, changed to full canopy: "+replaced+"\nHands clips: "+string.Join(",",clips.Select(c=>c.name)));
  ServiceBuild.RebakeV13(s);EditorSceneManager.MarkSceneDirty(s.gameObject.scene);EditorSceneManager.SaveScene(s.gameObject.scene);AssetDatabase.SaveAssets();
  ServiceV16Audit.Preview(s,"Finish");var cam=s.View;cam.cullingMask=-1;cam.transform.position=new Vector3(-63,2.5f,92);cam.transform.LookAt(new Vector3(-68,2,92));foreach(var c in clips.Where(c=>c.name.EndsWith("relax")||c.name.EndsWith("jab.R"))){c.SampleAnimation(model,c.length*.4f);ServiceV16Audit.Capture(cam,Path.Combine(ServiceV16Audit.Work,"PreviewV16Finish","hands-"+c.name.Split('|').Last()+".png"));}
  ServiceV16Audit.Open();ServiceQuickBuild.Build();
 }
}}
