using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Object=UnityEngine.Object;
namespace ServiceGameV2.Editor {public static class ServiceV16Cast {
 static List<string> log=new List<string>();
 static Material Mat(string name,Texture2D map,Texture2D normal=null){string path="Assets/ServiceArt/V16 "+name+".mat";var m=AssetDatabase.LoadAssetAtPath<Material>(path);if(!m){m=new Material(Shader.Find("Universal Render Pipeline/Lit"));AssetDatabase.CreateAsset(m,path);}m.SetTexture("_BaseMap",map);m.SetFloat("_Smoothness",.22f);m.SetFloat("_Cull",0);if(normal){var imp=(TextureImporter)AssetImporter.GetAtPath(AssetDatabase.GetAssetPath(normal));imp.textureType=TextureImporterType.NormalMap;imp.maxTextureSize=2048;imp.SaveAndReimport();m.SetTexture("_BumpMap",normal);m.EnableKeyword("_NORMALMAP");}EditorUtility.SetDirty(m);return m;}
 static GameObject Person(string name,Transform parent){var folder="Assets/External/Renderpeople/"+name+"/";var path=AssetDatabase.FindAssets("t:Model",new[]{folder.TrimEnd('/')}).Select(AssetDatabase.GUIDToAssetPath).First();var source=Object.Instantiate(AssetDatabase.LoadAssetAtPath<GameObject>(path),parent);source.name=name+" — authored resident";var texture=AssetDatabase.FindAssets("t:Texture2D",new[]{folder}).Select(AssetDatabase.GUIDToAssetPath).First(p=>p.EndsWith("_dif.jpg"));var normal=texture.Replace("_dif.jpg","_norm.jpg");var m=Mat(name,AssetDatabase.LoadAssetAtPath<Texture2D>(texture),AssetDatabase.LoadAssetAtPath<Texture2D>(normal));foreach(var r in source.GetComponentsInChildren<Renderer>())r.sharedMaterial=m;
  var anim=source.GetComponent<Animation>();var clip=AssetDatabase.LoadAllAssetsAtPath(path).OfType<AnimationClip>().First(c=>!c.name.StartsWith("__"));anim.clip=clip;anim.playAutomatically=true;anim.wrapMode=WrapMode.Loop;clip.SampleAnimation(source,1);foreach(AnimationState st in anim)st.wrapMode=WrapMode.Loop;return source;
 }
 public static void Apply(){var s=ServiceV16Audit.Open();var cast=new GameObject("County residents — recorded animation").transform;cast.SetParent(s.transform,false);var residents=cast.gameObject.AddComponent<ServiceResidents>();
  foreach(int index in new[]{0,4}){var p=s.Properties.Single(x=>x.Index==index);var human=Person("Sophia",cast);human.transform.position=p.Door.position-p.Door.forward*.9f;human.transform.rotation=Quaternion.LookRotation(p.Door.forward);if(index==0)residents.Correll=human;else residents.Bell=human;}
  var worker=Person("Nathan",cast);residents.DepotWorker=worker.transform;residents.WorkerAnimation=worker.GetComponent<Animation>();residents.WalkFrom=new Vector3(-13,0,-6);residents.WalkTo=new Vector3(-13,0,3);worker.transform.position=residents.WalkFrom;
  const string arms="Assets/External/DrillimpactArms/arms_rig.fbx";var importer=(ModelImporter)AssetImporter.GetAtPath(arms);importer.globalScale=.01f;importer.SaveAndReimport();var root=new GameObject("Authored first person hands").transform;root.SetParent(s.View.transform,false);root.localPosition=new Vector3(0,-1.74315f,0);var mesh=Object.Instantiate(AssetDatabase.LoadAssetAtPath<GameObject>(arms),root);mesh.transform.localPosition=Vector3.zero;mesh.transform.localRotation=Quaternion.identity;var hands=root.gameObject.AddComponent<ServiceHands>();hands.Rig=mesh.GetComponent<Animation>();var relax=AssetDatabase.LoadAllAssetsAtPath(arms).OfType<AnimationClip>().First(c=>c.name.EndsWith("|relax"));hands.Rig.clip=relax;hands.Rig.playAutomatically=true;foreach(AnimationState state in hands.Rig)state.wrapMode=WrapMode.Loop;relax.SampleAnimation(mesh,0);
  var skin=Mat("Drillimpact hands",AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/External/DrillimpactArms/arms_01.png"));foreach(var r in mesh.GetComponentsInChildren<Renderer>()){r.sharedMaterial=skin;r.shadowCastingMode=UnityEngine.Rendering.ShadowCastingMode.Off;}foreach(var r in mesh.GetComponentsInChildren<SkinnedMeshRenderer>()){r.updateWhenOffscreen=true;var baked=new Mesh();r.BakeMesh(baked);var bounds=new Bounds();bool first=true;foreach(var v in baked.vertices){var pt=r.transform.TransformPoint(v);if(first){bounds=new Bounds(pt,Vector3.zero);first=false;}else bounds.Encapsulate(pt);}log.Add("HANDS posed bounds="+bounds);Object.DestroyImmediate(baked);}
  // The source dog is a seated rigged sculpt. Keep its authored pose; do not slide a static dog around.
  var dog=s.transform.Find("Correll yard dog");foreach(Transform child in dog.Cast<Transform>().ToArray())Object.DestroyImmediate(child.gameObject);var dogModel=Object.Instantiate(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/External/PawelShepherd/Shepherd-seated.fbx"),dog);dogModel.name="Paweł Wałasiewicz — seated German Shepherd";dogModel.transform.localPosition=Vector3.zero;dogModel.transform.localRotation=Quaternion.Euler(0,90,0);
  var coat=Mat("Shepherd coat",AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/External/PawelShepherd/dog2_C.png"),AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/External/PawelShepherd/dog_N2.png"));var eyes=Mat("Shepherd eyes",AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/External/PawelShepherd/IRIS.jpg"));foreach(var r in dogModel.GetComponentsInChildren<Renderer>())r.sharedMaterial=r.name.Contains("eye")?eyes:coat;
  var dogBounds=dogModel.GetComponentsInChildren<Renderer>().Select(r=>r.bounds).Aggregate((a,b)=>{a.Encapsulate(b);return a;});dogModel.transform.localPosition+=Vector3.up*(dog.position.y-dogBounds.min.y);log.Add("DOG "+dogBounds);
  EditorSceneManager.MarkSceneDirty(s.gameObject.scene);EditorSceneManager.SaveScene(s.gameObject.scene);AssetDatabase.SaveAssets();File.WriteAllLines(Path.Combine(ServiceV16Audit.Work,"v16-cast.txt"),log);
  ServiceV16Audit.Preview(s,"Cast");ServiceQuickBuild.Build();
 }
}}
