using UnityEngine;
using UnityEditor;
using System.Collections.Generic;
namespace ServiceGameV2.Editor {
// Modelled in metres. The cabin is a separate first-person layer to avoid exterior-shell clipping.
public static class ServiceCockpit {
 static Transform root;static Material vinyl,trim,black,glow;static int serial;
 static Vector3 V(float x,float y,float z)=>new Vector3(x,y,z);
 static Material Material(string name,Color color,bool lit=true){var m=new Material(Shader.Find(lit?"Universal Render Pipeline/Lit":"Universal Render Pipeline/Unlit"));m.SetColor("_BaseColor",color);if(lit)m.SetFloat("_Smoothness",.28f);AssetDatabase.CreateAsset(m,"Assets/ServiceArt/Materials/"+name+".mat");return m;}
 static GameObject Part(string name,Vector3 pos,Vector3 size,Material mat,Transform parent=null){var o=GameObject.CreatePrimitive(PrimitiveType.Cube);Object.DestroyImmediate(o.GetComponent<Collider>());o.name=name;o.transform.SetParent(parent?parent:root,false);o.transform.localPosition=pos;o.transform.localScale=size;o.GetComponent<Renderer>().sharedMaterial=mat;return o;}
 static Transform Empty(string name,Vector3 pos,Transform parent=null){var t=new GameObject(name).transform;t.SetParent(parent?parent:root,false);t.localPosition=pos;return t;}
 static void Mesh(string name,List<Vector3> vertices,List<int> triangles,Transform parent,Material mat){var mesh=new Mesh{name=name};mesh.SetVertices(vertices);mesh.SetTriangles(triangles,0);mesh.RecalculateNormals();mesh.RecalculateBounds();AssetDatabase.CreateAsset(mesh,"Assets/ServiceArt/Meshes/Cockpit "+name+serial+++".asset");parent.gameObject.AddComponent<MeshFilter>().sharedMesh=mesh;parent.gameObject.AddComponent<MeshRenderer>().sharedMaterial=mat;}
 static void Ring(Transform parent,float radius,float tube,Material mat){var v=new List<Vector3>();var t=new List<int>();for(int i=0;i<64;i++)for(int j=0;j<8;j++){float a=i*Mathf.PI/32,b=j*Mathf.PI/4;v.Add(V(Mathf.Cos(a)*(radius+tube*Mathf.Cos(b)),Mathf.Sin(a)*(radius+tube*Mathf.Cos(b)),tube*Mathf.Sin(b)));int k=i*8+j,n=i*8+(j+1)%8,q=((i+1)%64)*8+j,r=((i+1)%64)*8+(j+1)%8;t.AddRange(new[]{k,n,q,n,r,q});}Mesh(parent.name,v,t,parent,mat);}
 static TextMesh Text(string text,Vector3 pos,float size,Transform parent=null){var tm=Empty(text,pos,parent).gameObject.AddComponent<TextMesh>();tm.text=text;tm.font=AssetDatabase.LoadAssetAtPath<Font>("Assets/Resources/Fonts/Barlow-Regular.ttf");tm.fontSize=96;tm.characterSize=size/9.6f;tm.anchor=TextAnchor.MiddleCenter;tm.color=new Color(.78f,.76f,.6f);tm.GetComponent<Renderer>().sharedMaterial=tm.font.material;return tm;}
 static Transform Dial(string name,Vector3 pos,float radius,string units){var face=Empty(name,pos);var disk=GameObject.CreatePrimitive(PrimitiveType.Cylinder);Object.DestroyImmediate(disk.GetComponent<Collider>());disk.transform.SetParent(face,false);disk.transform.localRotation=Quaternion.Euler(90,0,0);disk.transform.localScale=V(radius*2,.003f,radius*2);disk.GetComponent<Renderer>().sharedMaterial=black;Ring(face,radius,.004f,trim);for(int i=0;i<=12;i++){float a=Mathf.Lerp(220,-40,i/12f)*Mathf.Deg2Rad;var tick=Part("Dial graduation",V(Mathf.Cos(a)*radius*.83f,Mathf.Sin(a)*radius*.83f,-.006f),V(.002f,radius*.13f,.001f),glow,face);tick.transform.localRotation=Quaternion.Euler(0,0,a*Mathf.Rad2Deg-90);if(i%3==0)Text((units=="RPM"?i*.5f:i*5).ToString("0.#"),V(Mathf.Cos(a)*radius*.62f,Mathf.Sin(a)*radius*.62f,-.007f),.018f,face);}
 Text(units,V(0,-radius*.12f,-.008f),.013f,face);var needle=Empty("Needle",V(0,0,-.012f),face);Part("Needle pointer",V(0,radius*.33f,0),V(.003f,radius*.66f,.002f),glow,needle);needle.localRotation=Quaternion.Euler(0,0,130);return needle;}
 public static void Create(CountyScene scene){serial=0;root=Empty("County vehicle interior",Vector3.zero,scene.Car);scene.Cockpit=root.gameObject;
 vinyl=Material("Cabin vinyl",new Color(.12f,.14f,.13f));trim=Material("Cabin fittings",new Color(.28f,.31f,.29f));black=Material("Instrument faces",new Color(.012f,.017f,.015f));glow=Material("Instrument markings",new Color(.65f,.56f,.34f),false);
 // A shaped dashboard cross-section: bevelled brow, recessed fascia, lower kick panel.
 var section=new[]{new Vector2(.63f,.32f),new Vector2(.96f,.32f),new Vector2(1.015f,.40f),new Vector2(1.005f,.90f),new Vector2(.90f,1.02f),new Vector2(.58f,.85f)};
 var verts=new List<Vector3>();var tris=new List<int>();for(int j=0;j<section.Length;j++){int k=(j+1)%section.Length,n=verts.Count;verts.Add(V(-.86f,section[j].x,section[j].y));verts.Add(V(.86f,section[j].x,section[j].y));verts.Add(V(-.86f,section[k].x,section[k].y));verts.Add(V(.86f,section[k].x,section[k].y));tris.AddRange(new[]{n,n+2,n+1,n+1,n+2,n+3});}Mesh("Dashboard",verts,tris,Empty("Shaped dashboard",Vector3.zero),vinyl);
 Part("Recessed instrument panel",V(-.34f,.945f,.309f),V(.52f,.18f,.012f),black);
 scene.SpeedNeedle=Dial("Speedometer",V(-.45f,.966f,.292f),.074f,"MPH");scene.RevNeedle=Dial("Tachometer",V(-.23f,.966f,.292f),.058f,"RPM");
 scene.Odometer=Text("000.0 mi",V(-.34f,.866f,.287f),.030f);Part("Glovebox inset",V(.48f,.785f,.317f),V(.53f,.18f,.015f),black);Part("Glovebox latch",V(.48f,.858f,.299f),V(.07f,.015f,.012f),trim);Text("COUNTY FLEET  /  04",V(.48f,.922f,.306f),.018f);
 Part("Radio face",V(.12f,.83f,.303f),V(.27f,.095f,.022f),black);Text("88.5   FM",V(.12f,.845f,.285f),.027f);for(int i=0;i<5;i++)Part("Radio preset",V(.035f+i*.043f,.805f,.28f),V(.026f,.008f,.008f),trim);
 foreach(float x in new[]{-.72f,.71f}){Part("Air vent recess",V(x,.955f,.315f),V(.17f,.074f,.021f),black);for(int i=0;i<4;i++)Part("Vent slat",V(x,.93f+i*.016f,.30f),V(.15f,.004f,.012f),trim);}
 scene.SteeringWheel=Empty("Steering wheel",V(-.34f,.87f,.15f));scene.SteeringWheel.localRotation=Quaternion.Euler(18,0,0);Ring(scene.SteeringWheel,.174f,.015f,vinyl);Part("Horn pad",Vector3.zero,V(.13f,.064f,.035f),trim,scene.SteeringWheel);Part("Wheel spoke",Vector3.zero,V(.32f,.022f,.014f),trim,scene.SteeringWheel);Part("Lower spoke",V(0,-.085f,0),V(.024f,.15f,.013f),trim,scene.SteeringWheel);
 foreach(int side in new[]{-1,1}){var pillar=Part("Windshield pillar",V(side*.82f,1.345f,.73f),V(.032f,.92f,.038f),vinyl);pillar.transform.localRotation=Quaternion.Euler(-25,0,side*3);Part("Door card",V(side*.86f,.63f,-.27f),V(.055f,.57f,1.48f),vinyl);Part("Window sill",V(side*.84f,.96f,-.27f),V(.08f,.04f,1.48f),trim);Part("Door armrest",V(side*.79f,.67f,-.25f),V(.09f,.055f,.4f),black);Part("Door release",V(side*.795f,.84f,-.1f),V(.012f,.025f,.12f),trim);Part("Seat cushion",V(side*.40f,.43f,-.53f),V(.63f,.13f,.57f),vinyl);var back=Part("Seat back",V(side*.4f,.8f,-.9f),V(.63f,.72f,.14f),vinyl);back.transform.localRotation=Quaternion.Euler(-9,0,0);}
 Part("Cabin roof lining",V(0,1.78f,-.24f),V(1.75f,.04f,1.85f),vinyl);Part("Cabin rear wall",V(0,.78f,-1.02f),V(1.75f,.65f,.05f),vinyl);Part("Rear window surround",V(0,1.55f,-1.02f),V(1.75f,.28f,.05f),vinyl);Part("Floor",V(0,.29f,-.12f),V(1.72f,.035f,2.05f),black);Part("Footwell firewall",V(0,.5f,.73f),V(1.73f,.46f,.055f),black);
 // Functional cabin fittings, kept clear of the driver's sight line.
 foreach(float x in new[]{-.005f,.237f}){var knob=GameObject.CreatePrimitive(PrimitiveType.Cylinder);Object.DestroyImmediate(knob.GetComponent<Collider>());knob.name="Radio tuning knob";knob.transform.SetParent(root,false);knob.transform.localPosition=V(x,.837f,.275f);knob.transform.localRotation=Quaternion.Euler(90,0,0);knob.transform.localScale=V(.025f,.014f,.025f);knob.GetComponent<Renderer>().sharedMaterial=trim;}
 Part("Steering column",V(-.34f,.76f,.34f),V(.065f,.065f,.28f),black);
 var stalk=Part("Indicator stalk",V(-.48f,.79f,.17f),V(.2f,.013f,.016f),black);stalk.transform.localRotation=Quaternion.Euler(0,12,-10);
 Part("Transmission tunnel",V(0,.41f,-.24f),V(.19f,.18f,.9f),vinyl);Part("Gear lever",V(.06f,.63f,-.21f),V(.014f,.34f,.014f),trim);
 var shift=GameObject.CreatePrimitive(PrimitiveType.Sphere);Object.DestroyImmediate(shift.GetComponent<Collider>());shift.name="Gear knob";shift.transform.SetParent(root,false);shift.transform.localPosition=V(.06f,.80f,-.21f);shift.transform.localScale=V(.047f,.042f,.047f);shift.GetComponent<Renderer>().sharedMaterial=black;
 foreach(float x in new[]{-.45f,-.27f}){var pedal=Part("Pedal",V(x,.37f,.53f),V(.07f,.025f,.11f),trim);pedal.transform.localRotation=Quaternion.Euler(-25,0,0);}
 Part("Mirror stem",V(0,1.57f,.74f),V(.016f,.13f,.016f),trim);Part("Rearview mirror housing",V(0,1.52f,.74f),V(.22f,.074f,.028f),black);Part("Rearview glass",V(0,1.52f,.724f),V(.20f,.057f,.003f),trim);
 foreach(float x in new[]{-.43f,.43f})Part("Folded sun visor",V(x,1.7f,.49f),V(.52f,.027f,.19f),vinyl);
 var light=Empty("Instrument spill",V(-.32f,1.26f,-.1f)).gameObject.AddComponent<Light>();light.color=new Color(.76f,.75f,.6f);light.intensity=.65f;light.range=1.8f;light.cullingMask=1<<10;
 foreach(var t in root.GetComponentsInChildren<Transform>())t.gameObject.layer=10;
 scene.DriverSeat.localPosition=V(-.34f,1.29f,-.35f);
 }
}}

